"""empty message

Revision ID: 0808468b93f8
Revises: 
Create Date: 2019-05-17 00:21:46.752037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0808468b93f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types')
    # ### end Alembic commands ###
